In [2]:
# 1. Create a null vector of size 10 but the fifth value which is 1.
import numpy as np
x=np.zeros(10) 
x[4]=1  
print(x)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [3]:
# 2. Create a vector with values ranging from 10 to 49.
import numpy as np
v = np.arange(10,50)
print("Array:")
print(v)



Array:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [4]:
#3. Create a 3x3 matrix with values ranging from 0 to 8

import numpy as np
x = np.arange(9).reshape(3,3)
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

x = np.array([1,2,0,0,4,0])
print(x)
np.nonzero(x)


[1 2 0 0 4 0]


(array([0, 1, 4], dtype=int64),)

In [6]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.

a=np.random.random((10,10))
print('Maximum value is: ',a.max())
print('Minimum value is: ',a.min())

Maximum value is:  0.9856463334351172
Minimum value is:  0.0012621755368189547


In [7]:
# 6. Create a random vector of size 30 and find the mean value.

g=np.random.random(30)
print("Original Array :\n",g,"\n")
print("Mean of given array",np.mean(g))

Original Array :
 [0.22760875 0.19368074 0.06455122 0.82200963 0.40162408 0.6286542
 0.94069532 0.09842375 0.38638775 0.42937177 0.25992716 0.13516575
 0.76912673 0.4161826  0.5646043  0.52171214 0.37791891 0.0885256
 0.34026984 0.56068681 0.67727195 0.3938959  0.52598639 0.57159834
 0.44194412 0.92689757 0.37869462 0.20354172 0.90846186 0.08811206] 

Mean of given array 0.4447843859573226
